### ISSUE TITLE
Syntax error in the example code?

### ISSUE THREAD

**Issue by joonas-fi** [FrigoEU/typescript-safe-router#1]
First off, thanks for making this project! I was thinking of something like this for the compiler to help with the most obvious bugs, but didn't have the TypeScript ninja skills required..

This code example:
```
makeRouter(
  messages, ({startDate: Date}) => {
    console.log("We've navigated to the messages page!")
    return null;
  }).registerRoute(
  employees, ({employeeId: number}) => {
    console.log("We've navigated to the employees page!")
    return null;
  });
```

Simplified, the code does this:

```
const hello = ({foo: string}) => { console.log('oh hai'); };
```

The argument to the callback is not named. That yields cryptic-ish TypeScript error `'string' is declared but its value is never read` and `binding element 'string' implicitly has an 'any' type`.

(Same issue is present under the "A full example with React" heading)

The code in the example should probably read something like this:

```
makeRouter(
  messages, (opts: {startDate: Date}) => {
    console.log("We've navigated to the messages page!");
    return null;
  }).registerRoute(
  employees, (opts: {employeeId: number}) => {
    console.log("We've navigated to the employees page! Employee number: " + opts.employeeId.toString());
    return null;
  });
```

That works, but seems too complicated also, because TypeScript compiler knows the type of the "opts" argument, and therefore we can just omit it:

```
makeRouter(
  messages, (opts) => {
    console.log("We've navigated to the messages page!");
    return null;
  }).registerRoute(
  employees, (opts) => {
    console.log("We've navigated to the employees page! Employee number: " + opts.employeeId.toString());
    return null;
  });
```

Looks much cleaner, and the compiler errors if you'd access `opts.fieldThatDoesNotExist`!

**Comment by FrigoEU** [comment]
I'm OK with that, I'll fix it :).
